#GoAccess
log_format lb_detailed '$remote_addr - [$time_local] "$request" '
                       '$status $body_bytes_sent '
                       'rt=$request_time '
                       'upstream=$upstream_addr '
                       'upstream_rt=$upstream_response_time' ;

access_log /var/log/nginx/lb_access.log lb_detailed;


#Rate Limiting
limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;


#ROUND ROBIN
upstream backend {
   server 192.168.56.11 max_fails=3 fail_timeout=30s;
   server 192.168.56.12 max_fails=3 fail_timeout=30s;
   server 192.168.56.13 max_fails=3 fail_timeout=30s;
}

#Round Robin Weighted
#upstream backend {
#    server 192.168.56.11 weight=7 max_fails=3 fail_timeout=30s;
#    server 192.168.56.12 weight=5 max_fails=3 fail_timeout=30s;
#    server 192.168.56.13 weight=2 max_fails=3 fail_timeout=30s;
#}

#Least Connections
#upstream backend {
#    server 192.168.56.11 max_fails=3 fail_timeout=30s;
#    server 192.168.56.12 max_fails=3 fail_timeout=30s;
#    server 192.168.56.13 max_fails=3 fail_timeout=30s;
#}

#IP Hash
#upstream backend {
#   ip_hash;
#   server 192.168.56.11 max_fails=3 fail_timeout=30s;
#   server 192.168.56.12 max_fails=3 fail_timeout=30s;
#   server 192.168.56.13 max_fails=3 fail_timeout=30s;
#}

#Consistent Hashing 
#upstream backend {
#   hash $request_uri consistent;
#   server 192.168.56.11 max_fails=3 fail_timeout=30s;
#   server 192.168.56.12 max_fails=3 fail_timeout=30s;
#   server 192.168.56.13 max_fails=3 fail_timeout=30s;
#}

server {
    listen 443 ssl;
    server_name 192.168.1.120;

    ssl_certificate /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/private/nginx.key;

    location / {
      # limit_req zone=one burst=20 nodelay;
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /report.html {
        alias /var/www/html/report.html;
    }
}




